### ISSUE TITLE
Git rebase strategy doesn't create directory for release

### ISSUE THREAD

**Issue by Trudko** [andres-montanez/Magallanes#185] opened 2015-01-23 11:30 UTC
Hi, I am trying a git rebase strategy and according to a log and from what I checked in the code it seems that during git rebase strategy a directory for the release is not created. Here is start of the log for last release.
```
2015-01-23 11:10:38 -- Starting Magallanes--------------
2015-01-23 11:10:38 -- Logging enabled $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c
2015-01-23 11:10:38 -- Logging enabled: /path/to/app/.mage/logs/log-20150123-111038.log
2015-01-23 11:10:38 -- Deploy summary
2015-01-23 11:10:38 -- Environment: production----------
2015-01-23 11:10:38 -- Release ID:  20150123111038------
2015-01-23 11:10:38 -- ---- Executing: $ rm /tmp/magefnXdW5 /tmp/magefnXdW5.tar.gz
2015-01-23 11:10:38 -- No Pre-Deployment tasks defined.
2015-01-23 11:10:38 -- Deploying to server.com
2015-01-23 11:10:38 -- Running Deploy via Git Rebase [built-in] ...
2015-01-23 11:10:38 -- Run remote command cd /var/www/app && cd releases/20150123111038 && git fetch origin
2015-01-23 11:10:38 -- ---------------------------------path/to/app/releases/20150123111533 && app/console cache:clear --env=prod --no-warmup
2015-01-23 11:10:38 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c
\"cd /var/www/app && cd releases/20150123111038 && git fetch origin\""=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c
2015-01-23 11:10:38 -- sh: line 0: cd: releases/20150123111038: No such file or directoryo-warmup\""
```
Folder 20150123111038 isn't created and deployment failed.

**Comment by dennisusdev** [comment] 2015-01-27 18:52
+1 on this, using v1.0.3 - reverting to 1.0.2 resolved the issue

**Comment by eps90** [comment] 2015-01-28 06:33
Thanks for reporting. I'll check that.

**Comment by lukezbihlyj** [comment] 2015-01-31 03:59
It looks like this is the relevant commit: https://github.com/andres-montanez/Magallanes/commit/92b22d52a3603b2b7c8f22b3baadc470ecb3bc36#diff-81da38bff73f46a53c72da138abfb492

The section to deal with releases was removed entirely, for an unknown reason.

**Comment by eps90** [comment] 2015-01-31 07:54
i think so. I've also found this while looking for differences between 1.0.2 and 1.0.3. I'll try to fix that today'.

**Comment by eps90** [comment] 2015-02-01 11:07
Hey, I've made a PR at #187. Take a look.
I've made a little research why this piece of code has been deleted. And I didn't find the answer. So @andres-montanez Can you also take a look? Maybe there was some reason to remove directory creation?
@Trudko @lukezbihlyj @dennisusdev Please test it, any feedback will be welcome

**Comment by spongeben** [comment] 2015-02-01 11:34
Hey!

I think there's the same issue with the rsync strategy (and maybe others...)
And as this one I think it was working fine with older releases of Mage. 
Didn't have time yet to check, I'll try to have a look at it

**Comment by eps90** [comment] 2015-02-01 13:00
@spongeben The problem with `GitRebase` strategy was that directory wasn't created at all while in `RsyncTask` it's done. Could you provide some logs of calling deployment with rsync?

**Comment by eps90** [comment] 2015-02-06 19:51
I've pushed a commit with remote directory fix (thanks for @lukezbihlyj  for spotting it).

**Comment by spongeben** [comment] 2015-02-09 11:39
@eps90 my bad...it was indeed unrelated with this one. But there's a bug with the rsync strategy with the rsync_copy option enabled. I'll open a new issue or post a PR

**Comment by eps90** [comment] 2015-02-09 11:46
Great, if you know where's the problem exactly, that would be awesome :)

**Comment by lucascherifi** [comment] 2015-02-20 10:34
+1

**Comment by eps90** [comment] 2015-02-24 20:22
@Trudko @dennisusdev @lukezbihlyj @lucascherifi 
I've merged the #187 PR so you can install the Magallanes from develop branch (in composer you type `dev-develop` as version) and tell does it work for you. Any feedback welcome. If it's ok, it's gonna be merged in the nearest Magallanes version :)

**Comment by Trudko** [comment] 2015-02-24 20:32
Cool will test tomorrow morning.

**Comment by Trudko** [comment] 2015-02-25 13:33
Well I've tried it and folder is created on git rebase strategy but now after command  cd releases/20150225132014 && git checkout master\"" I get error that one of my files needs merge and error: you need to resolve your current index first. Not sure how this can happen if mage is pulling from remote. What am I missing?

**Comment by eps90** [comment] 2015-02-25 13:43
Ok, I'll take a look on that.

**Comment by lucascherifi** [comment] 2015-02-27 11:47
It cannot work... you mkdir then you git checkout my_branch 

2015-02-27 11:41:42 -- Running Deploy via Git Rebase [built-in] ... 
2015-02-27 11:41:42 -- Run remote command cd /home/******/public_html/**********/current && mkdir -p /home/******/public_html/**********/current/releases/20150227114142
2015-02-27 11:41:42 -- ---------------------------------
2015-02-27 11:41:42 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no **********@**** "sh -c \"cd /home/******/public_html/**********/current && mkdir -p /home/******/public_html/**********/current/releases/20150227114142\""
2015-02-27 11:41:42 -- 
2015-02-27 11:41:42 -- ---------------------------------
2015-02-27 11:41:42 -- Run remote command cd /home/******/public_html/**********/current && cd releases/20150227114142 && git fetch origin
2015-02-27 11:41:42 -- ---------------------------------
2015-02-27 11:41:42 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no **********@**** "sh -c \"cd /home/******/public_html/**********/current && cd releases/20150227114142 && git fetch origin\""
2015-02-27 11:41:44 -- 
2015-02-27 11:41:44 -- ---------------------------------
2015-02-27 11:41:44 -- Run remote command cd /home/******/public_html/**********/current && cd releases/20150227114142 && git checkout develop
2015-02-27 11:41:44 -- ---------------------------------
2015-02-27 11:41:44 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no **********@**** "sh -c \"cd /home/******/public_html/**********/current && cd releases/20150227114142 && git checkout develop\""
2015-02-27 11:41:44 -- Already on 'develop'
2015-02-27 11:41:44 -- ---------------------------------
2015-02-27 11:41:44 -- Run remote command cd /home/******/public_html/**********/current && cd releases/20150227114142 && git checkout develop
2015-02-27 11:41:44 -- ---------------------------------
2015-02-27 11:41:44 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no **********@**** "sh -c \"cd /home/******/public_html/**********/current && cd releases/20150227114142 && git checkout develop\""
2015-02-27 11:41:44 -- Already on 'develop'
2015-02-27 11:41:44 -- ---------------------------------
2015-02-27 11:41:44 -- Run remote command cd /home/******/public_html/**********/current && cd releases/20150227114142 && git stash
2015-02-27 11:41:44 -- ---------------------------------
2015-02-27 11:41:44 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no **********@**** "sh -c \"cd /home/******/public_html/**********/current && cd releases/20150227114142 && git stash\""
2015-02-27 11:41:44 -- No local changes to save
2015-02-27 11:41:44 -- ---------------------------------
2015-02-27 11:41:44 -- Run remote command cd /home/******/public_html/**********/current && cd releases/20150227114142 && git rebase origin/develop
2015-02-27 11:41:44 -- ---------------------------------
2015-02-27 11:41:44 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no **********@**** "sh -c \"cd /home/******/public_html/**********/current && cd releases/20150227114142 && git rebase origin/develop\""
2015-02-27 11:41:45 -- Current branch develop is up to date.
2015-02-27 11:41:45 -- ---------------------------------

**Comment by Trudko** [comment] 2015-03-05 17:38
Any update on this?

**Comment by eps90** [comment] 2015-03-05 18:05
Sorry guys, I have completely no time in this week. I don't want to promise anything but I think the earliest day when I can look into the code is Saturday morning (CET)

**Comment by Trudko** [comment] 2015-03-05 18:10
No problem. My intent wasn't to push you, no need to apologize :) Thanks for the work you did so far!

**Comment by eps90** [comment] 2015-03-05 18:13
Yeah, I know, but as a collaborator I feel responsible for this project and I want to keep the highest quality of the project with no keeping smells and temporary solutions. So I need some free time to analyze the code and find the best solution :) As you can see, I've just merged solving the problem partly, but it's still not good enough. So sorry again for delay, I hope I'm gonna fix it immediately! :)

**Comment by eps90** [comment] 2015-03-07 14:05
@Trudko Can you pass your config and logs to make me reproduce the errors? I'm doing it with realses enabled and everything works fine.

**Comment by Trudko** [comment] 2015-03-09 09:11
Sure. I am using dev master version.

```
#integration
deployment:
  strategy: git-rebase
  user: release
  from: ./
  to: /path/to/project
  excludes:
releases:
  enabled: true
  max: 10
  symlink: current
  directory: releases
hosts:
    - server.com
tasks:
  pre-deploy:
  on-deploy:
  post-release:
  post-deploy:
```


```
2015-03-09 09:01:30 -- Starting Magallanes
2015-03-09 09:01:30 -- Logging enabled
2015-03-09 09:01:30 -- Logging enabled: /data/www/trudko/project/.mage/logs/log-20150309-090130.log
2015-03-09 09:01:30 -- Deploy summary
2015-03-09 09:01:30 -- Environment: integration
2015-03-09 09:01:30 -- Release ID:  20150309090130
2015-03-09 09:01:30 --
2015-03-09 09:01:30 -- No Pre-Deployment tasks defined.
2015-03-09 09:01:30 -- Deploying to server.com
2015-03-09 09:01:30 -- Running Deploy via Git Rebase [built-in] ...
2015-03-09 09:01:30 -- Run remote command cd /path/to/project && mkdir -p /path/to/project/releases/20150309090130
2015-03-09 09:01:30 -- ---------------------------------
2015-03-09 09:01:30 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && mkdir -p /path/to/project/releases/20150309090130\""
2015-03-09 09:01:31 --
2015-03-09 09:01:31 -- ---------------------------------
2015-03-09 09:01:31 -- Run remote command cd /path/to/project && cd releases/20150309090130 && git fetch origin
2015-03-09 09:01:31 -- ---------------------------------
2015-03-09 09:01:31 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && cd releases/20150309090130 && git fetch origin\""
2015-03-09 09:01:32 --
2015-03-09 09:01:32 -- ---------------------------------
2015-03-09 09:01:32 -- Run remote command cd /path/to/project && cd releases/20150309090130 && git checkout master
2015-03-09 09:01:32 -- ---------------------------------
2015-03-09 09:01:32 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && cd releases/20150309090130 && git checkout master\""
2015-03-09 09:01:32 -- .mage/tasks/Translations.php: needs merge
error: you need to resolve your current index first
2015-03-09 09:01:32 -- ---------------------------------
2015-03-09 09:01:32 -- Run remote command cd /path/to/project && cd releases/20150309090130 && git checkout master
2015-03-09 09:01:32 -- ---------------------------------
2015-03-09 09:01:32 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && cd releases/20150309090130 && git checkout master\""
2015-03-09 09:01:33 -- .mage/tasks/Translations.php: needs merge
error: you need to resolve your current index first
2015-03-09 09:01:33 -- ---------------------------------
2015-03-09 09:01:33 -- Run remote command cd /path/to/project && cd releases/20150309090130 && git stash
2015-03-09 09:01:33 -- ---------------------------------
2015-03-09 09:01:33 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && cd releases/20150309090130 && git stash\""
2015-03-09 09:01:33 -- .mage/tasks/Translations.php: needs merge
.mage/tasks/Translations.php: needs merge
.mage/tasks/Translations.php: unmerged (bc5fb5ef27064bb57917b0ad47d23202254193e5)
.mage/tasks/Translations.php: unmerged (b911a394a8bbc582fc47f273a142fd3c23c10f78)
.mage/tasks/Translations.php: unmerged (6eea1f981b796c8bea787ec3fcb7afdf6cc59868)
fatal: git-write-tree: error building trees
Cannot save the current index state
2015-03-09 09:01:33 -- ---------------------------------
2015-03-09 09:01:33 -- Run remote command cd /path/to/project && cd releases/20150309090130 && git rebase origin/master
2015-03-09 09:01:33 -- ---------------------------------
2015-03-09 09:01:33 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && cd releases/20150309090130 && git rebase origin/master\""
2015-03-09 09:01:34 -- .mage/tasks/Translations.php: needs merge
Cannot rebase: You have unstaged changes.
Additionally, your index contains uncommitted changes.
Please commit or stash them.
2015-03-09 09:01:34 -- ---------------------------------
2015-03-09 09:01:34 -- Run remote command cd /path/to/project && cd releases/20150309090130 && git stash pop
2015-03-09 09:01:34 -- ---------------------------------
2015-03-09 09:01:34 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && cd releases/20150309090130 && git stash pop\""
2015-03-09 09:01:35 -- No stash found.
2015-03-09 09:01:35 -- ---------------------------------
2015-03-09 09:01:35 -- FAIL
2015-03-09 09:01:35 -- Deployment to server.com completed: 0/1 tasks done.
2015-03-09 09:01:35 -- A total of 1 deployment tasks failed: ABORTING
2015-03-09 09:01:35 -- No Post-Deployment tasks defined.
2015-03-09 09:01:35 -- Time for deployment: 5 seconds.
2015-03-09 09:01:35 -- Average time per host: 5 seconds.
2015-03-09 09:01:35 -- Total time: 5 seconds.
2015-03-09 09:01:35 -- Command execution failed with following exit code: 1
2015-03-09 09:01:35 -- Finished Magallanes

**Comment by eps90** [comment] 2015-03-09 09:49
Great, thanks. I'll take a look on that in few hours (when I'll finish work)

**Comment by eps90** [comment] 2015-03-09 10:15
In meantime, look at your directory where `releases` and `current` directories are and check if there's a `.git` folder. If so, remove it. It looks like the ricochet from buggy deployment (before my PR was merged).

**Comment by Trudko** [comment] 2015-03-09 18:44
OK I will check that. Btw for this project I was using tar strategy, might that play a role?

**Comment by eps90** [comment] 2015-03-09 18:57
It shouldn't since you have releases enbled, that means that each deploy creates a directory named with directory id. So every time you run deploy, you should start from bare directory.
Things are different when you won't enable releases. Then everything comes into the same folder everytime. In the `GitRebase` case, Magallanes calls `git rebase` on your preoviously deployed sources.
In your case it looks like you ran deploy without releases first, then `.git` with local repository information has been created, there were some errors and then you run another release but into timestamped folder, but repository belonging there still referes into `.git` that belongs to parent.

**Comment by Trudko** [comment] 2015-03-10 08:46
So I 've removed .git folder from  project root(under which there is current and releases folders) and now I get diff error.

```
2015-03-10 08:42:24 -- Starting Magallanes
2015-03-10 08:42:24 -- Logging enabled
2015-03-10 08:42:24 -- Logging enabled: /pato/to/project/.mage/logs/log-20150310-084224.log
2015-03-10 08:42:24 -- Deploy summary
2015-03-10 08:42:24 -- Environment: integration
2015-03-10 08:42:24 -- Release ID:  20150310084224
2015-03-10 08:42:24 --
2015-03-10 08:42:24 -- No Pre-Deployment tasks defined.
2015-03-10 08:42:24 -- Deploying to server.com
2015-03-10 08:42:24 -- Running Deploy via Git Rebase [built-in] ...
2015-03-10 08:42:24 -- Run remote command cd /path/to/project && mkdir -p /path/to/project/releases/20150310084224
2015-03-10 08:42:24 -- ---------------------------------
2015-03-10 08:42:24 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && mkdir -p /path/to/project/releases/20150310084224\""
2015-03-10 08:42:25 --
2015-03-10 08:42:25 -- ---------------------------------
2015-03-10 08:42:25 -- Run remote command cd /path/to/project && cd releases/20150310084224 && git fetch origin
2015-03-10 08:42:25 -- ---------------------------------
2015-03-10 08:42:25 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && cd releases/20150310084224 && git fetch origin\""
2015-03-10 08:42:25 -- fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2015-03-10 08:42:25 -- ---------------------------------
2015-03-10 08:42:25 -- Run remote command cd /path/to/project && cd releases/20150310084224 && git checkout master
2015-03-10 08:42:25 -- ---------------------------------
2015-03-10 08:42:25 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && cd releases/20150310084224 && git checkout master\""
2015-03-10 08:42:26 -- fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2015-03-10 08:42:26 -- ---------------------------------
2015-03-10 08:42:26 -- Run remote command cd /path/to/project && cd releases/20150310084224 && git checkout master
2015-03-10 08:42:26 -- ---------------------------------
2015-03-10 08:42:26 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && cd releases/20150310084224 && git checkout master\""
2015-03-10 08:42:26 -- fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2015-03-10 08:42:26 -- ---------------------------------
2015-03-10 08:42:26 -- Run remote command cd /path/to/project && cd releases/20150310084224 && git stash
2015-03-10 08:42:26 -- ---------------------------------
2015-03-10 08:42:26 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && cd releases/20150310084224 && git stash\""
2015-03-10 08:42:27 -- fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2015-03-10 08:42:27 -- ---------------------------------
2015-03-10 08:42:27 -- Run remote command cd /path/to/project && cd releases/20150310084224 && git rebase origin/master
2015-03-10 08:42:27 -- ---------------------------------
2015-03-10 08:42:27 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && cd releases/20150310084224 && git rebase origin/master\""
2015-03-10 08:42:28 -- fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2015-03-10 08:42:28 -- ---------------------------------
2015-03-10 08:42:28 -- Run remote command cd /path/to/project && cd releases/20150310084224 && git stash pop
2015-03-10 08:42:28 -- ---------------------------------
2015-03-10 08:42:28 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@server.com "sh -c \"cd /path/to/project && cd releases/20150310084224 && git stash pop\""
2015-03-10 08:42:28 -- fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2015-03-10 08:42:28 -- ---------------------------------
2015-03-10 08:42:28 -- FAIL

**Comment by eps90** [comment] 2015-03-10 09:29
hmm, don't you need to pass `repository` to `deployment` node in config? It tries to do `git fetch` in a not-git-aware directory

**Comment by Trudko** [comment] 2015-03-11 14:13
@eps90 you were right I had missing repository parameter. It looks ok now :) It would be great to update documentation about params for git rebase because I didn't find much about it on main page.

**Comment by eps90** [comment] 2015-03-11 17:33
Ineed, documentation is necessary for many places here. I have somthing already written, when I'll finish, I'll do some PR with that :) Meanwhile, there's an issue for that. 
So, I'm happy you resolved your problem :) I'm closing this issue then :) Take care!

**Closed by eps90** 2015-03-11 17:33 UTC
Labels: Bug, Feedback Needed
