### ISSUE TITLE
Problem to deploy

### ISSUE THREAD

**Issue by matiux** [andres-montanez/Magallanes#274] opened 2015-12-07 10:24 UTC
I'm using magallanes on a new project but something not works.

```
Running Deploy via TarGz (with Releases) [built-in] ... FAIL
```

```
A total of 1 deployment tasks failed: ABORTING
```

This is the end part of log file

```
2015-12-07 10:19:20 -- ---------------------------------
2015-12-07 10:19:20 -- ---- Executing: $ rm /tmp/magebVWHmL /tmp/magebVWHmL.tar.gz
2015-12-07 10:19:20 -- 
2015-12-07 10:19:20 -- ---------------------------------
2015-12-07 10:19:20 -- FAIL
2015-12-07 10:19:20 -- Deployment to x.x.x.x completed: 0/1 tasks done.
2015-12-07 10:19:20 -- A total of 1 deployment tasks failed: ABORTING
2015-12-07 10:19:20 -- No Post-Deployment tasks defined.
2015-12-07 10:19:20 -- Time for deployment: 3 seconds.
2015-12-07 10:19:20 -- Average time per host: 3 seconds.
2015-12-07 10:19:20 -- Total time: 3 seconds.
2015-12-07 10:19:20 -- Finished Magallanes
```

**Comment by jhuet** [comment] 2015-12-07 22:57
Could have a look at your config file please ?

**Comment by matiux** [comment] 2015-12-08 22:35
#local
deployment:
  user: my_user
  from: ./
  to: /var/www/Project/Name
  excludes:
      - .idea
      - composer.lock
      - storage/app/logs/*
releases:
  enabled: true
  max: 5
  symlink: current
  directory: releases
hosts:
  - x.x.x.x
tasks:
  pre-deploy:
  on-deploy:
  post-release:
  post-deploy:

**Comment by jhuet** [comment] 2015-12-09 11:12
Is the `rm /tmp/magebVWHmL /tmp/magebVWHmL.tar.gz` command the only one that failed in your logs ? Has the script been able to create this archive ?

**Comment by matiux** [comment] 2015-12-10 08:16
Yes, is the only that fails.
The script creates the archive, in fact, there are a files in the destination server

**Comment by jhuet** [comment] 2015-12-10 22:36
I'm not sure what's happening there, does this archive still exists in `/tmp/magebVWHmL.tar.gz` ? If so, can you try to delete it with the same user you're using to execute the script ? Do you have an error somehow ?

**Comment by LTRocky** [comment] 2016-01-28 23:24
same problem here: 
2016-01-28 22:36:43 -- ---------------------------------
2016-01-28 22:36:43 -- ---------------------------------
2016-01-28 22:36:43 -- ---- Executing: $ rm -f /tmp/mage7ot0sN /tmp/mage7ot0sN.tar.gz
2016-01-28 22:36:43 -- 
2016-01-28 22:36:43 -- ---------------------------------
2016-01-28 22:36:43 -- FAIL

tmp folder is empty. Any solutions ?

**Comment by LTRocky** [comment] 2016-01-30 22:44
solution to my problem: make sure you have correct permissions to the files you are about to deploy.

**Comment by andres-montanez** [comment] 2017-01-02 23:11
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!

**Closed by andres-montanez** 2017-01-02 23:11 UTC
Labels: v1

**Comment by bogdanmanate** [comment] 2017-04-24 14:44
I'm having the same problem. I have already changed the rights on my project and on the tmp folders. 
@LTRocky Can you please tell me what rights have you changed ?

**Comment by LTRocky** [comment] 2017-04-24 17:58
@bogdanmanate it was long time ago... having hard time remembering, but looking from what I have written in my previous comment I would suggest to at first make sure that the problem is with permissions: just try running magallanes with sudo.
