### ISSUE TITLE
Undefined variable: currentCopy in RollbackTask.php

### ISSUE THREAD

**Issue by ParkMasakazu** [andres-montanez/Magallanes#206] opened 2015-03-11 03:10 UTC
Hi, I am thankful to always use the magallanes.
Thank you for the useful tool.
Recently, I was updated magallanes from v1.0.1 to v1.0.5.
But the following error After rollback occurred in v1.0.5.
```
$ mage releases rollback --release=-1 to:production
PHP Notice: Undefined variable: currentCopy in ./vendor/andres-montanez/magallanes/Mage/Task/BuiltIn/Releases/RollbackTask.php on line 140
```
This is the happy and help solve the problem.
Please continue the development of the future also a good tool.
Thanks you.

**Comment by ZesInternational** [comment] 2015-03-12 09:27
in Mage\Task\BuiltIn\Releases\RollbackTask at line 91 add:
```php
$currentCopy = $releasesDirectory . '/' . $releaseId;
```
then it will work again.

**Comment by eps90** [comment] 2015-03-12 10:42
@ZesInternational Could you make a PR with that?

**Comment by eps90** [comment] 2015-03-15 12:59
@ParkMasakazu Thanks to @ZesInternational the issue is fixed. Please install Magallanes from `develop` branch (in composer.json you need to pass `dev-develop` as version) and check if everything works fine :)

**Comment by ParkMasakazu** [comment] 2015-03-16 11:41
Hi, It's very quickly.
I have obtained from dev-develop, worked confirmation even here.
Thanks you.

**Comment by eps90** [comment] 2015-03-16 14:22
@ParkMasakazu So, can we close the issue then?

**Comment by ParkMasakazu** [comment] 2015-03-16 15:37
OK, No problem. Thanks!

**Comment by eps90** [comment] 2015-03-16 16:34
Fixed in #209

**Closed** 2015-03-16 16:33 UTC
